#!/bin/bash
# Copyright (C) 2016-2018 Graham R. Cobb
# Released under GPL V2 -- see LICENSE

# Note: the master version of this file is in git but it has to be checked
# and then stored somewhere like /usr/local/sbin/ to be safe to be run automatically by root.
# Never have root automatically run programs/scripts that can be modified by non-root users.

# btrfs-balance-slowly [options] <filter> <disk>
#
# Do a btrfs balance with frequent breaks.
#
# This script is designed to run a btrfs balance in portions, using the limit filter.
# There can be delays between portions, and there are hooks to allow services
# to be stopped during the balance portion and restarted again afterwards.
#

interval=600
limit=0
tlimit=3600
hook="true"
portion_tlimit=300

usage() {
        echo "Usage: $0 " '[options] <filter> <disk>'
        echo $'\t<filter>\tbalance filter, for example: -dusage=20,limit=10'
        echo $'\t<disk>\tdisk to balance, for example: /mnt/backup2'
        echo $'Options:'
        echo $'\t-l | --limit\t<count> - maximum number of portions, default' $limit
        echo $'\t-t | --time\t<seconds> - maximum total time (in seconds), default' $tlimit
        echo $'\t-T | --portion-time\t<seconds> - timeout for each balance portion (in seconds), default' $portion_tlimit
        echo $'\t-i | --interval\t<seconds> - delay between portions, default' $interval
        echo $'\t-h | --hook\t<command-or-function> - command to execute before/after portion of balance, default "true"'
}

while [ $# -gt 2 ]
do
    if [ "$1" = "-l" -o "$1" = "--limit" ]
    then
        limit=$2
        shift 2
    elif [ "$1" = "-t" -o "$1" = "--time" ]
    then
         tlimit=$2
         shift 2
    elif [ "$1" = "-T" -o "$1" = "--portion-time" ]
    then
         portion_tlimit=$2
         shift 2
    elif [ "$1" = "-i" -o "$1" = "--interval" ]
    then
         interval=$2
         shift 2
    elif [ "$1" = "-h" -o "$1" = "--hook" ]
    then
         hook=$2
         shift 2
    else
        echo "Unrecognised option $1"
        usage
        exit 98
    fi
done

if [ $# -ne 2 ]
then
    echo "Insufficient arguments"
    usage
    exit 97
fi

filter=$1
disk=$2

start-portion-timer() {
    test $portion_tlimit -eq 0 && return
    # Run a timer and cancel the balance if it expires
    ( for ((i=portion_tlimit; i-- ; )) ; do sleep 1 ; done; echo "Portion timeout ($portion_tlimit seconds)" ; btrfs balance status $disk ; btrfs balance cancel $disk ) &
    portion_timer=$!
}

stop-portion-timer() {
    test $portion_tlimit -eq 0 && return
    kill $portion_timer  2>/dev/null && wait $portion_timer 2>/dev/null
}

run-portion() {
    # Run one portion.  Returns success if at least one chunk was relocated.

    pre-balance-hook "$@"
    hookstatus=$?
    if [ $hookstatus -ne 0 ]
    then
        echo "Pre-balance hook failed ($hookstatus)"
        return $hookstatus
    fi

    start-portion-timer
    outfile="$(mktemp)"
    command time -v btrfs balance start "$@" >$outfile
    runstatus=$?
    stop-portion-timer
    cat $outfile

    post-balance-hook "$@"
    hookstatus=$?
    if [ $hookstatus -ne 0 ]
    then
        echo "Post-balance hook failed ($hookstatus)"
        runstatus=$hookstatus
    fi
        
    if [ $runstatus -eq 0 ]
    then
	# Look at the output to see if anything was done
	# Note: this check depends on the format of the btrfs balance output
	# but tries to fail-safe: if the output format changes we will return failure
	if ! grep --silent 'relocate [1-9]' $outfile
	then runstatus=99
	fi
    fi

    rm $outfile
    return $runstatus
}

pre-balance-hook() {
    $hook "pre" "$@"
}

post-balance-hook() {
    $hook "post" "$@"
}

# Hook function to stop mail handling during the balance
# Used for main data disk
hook-nomail() {
    retstatus=0
        
    if [ "$1" = "pre" ]
    then
        systemctl stop fetchmail  && systemctl stop postfix && systemctl stop dovecot
        retstatus=$?
        if [ $retstatus -ne 0 ]
        then
            # Stopping services failed. Try to start them again
            logger -s -t $0 "Stopping fetchmail, postfix or dovecot failed.  Trying restarting."
            systemctl start dovecot
            systemctl start postfix
            systemctl start fetchmail
        fi
    elif [ "$1" = "post" ]
    then
        systemctl start dovecot
        tempstatus=$?
        if [ $tempstatus -ne 0 ]
        then
            logger -s -t $0 "Could not restart dovecot: $tempstatus"
            retstatus=$tempstatus
            # Dovecot has failed, but go on and try to restart postfix and fetchmail anyway
        fi

        systemctl start postfix
        tempstatus=$?
        if [ $tempstatus -ne 0 ]
        then
            logger -s -t $0 "Could not restart postfix: $tempstatus"
            retstatus=$tempstatus
            # Postfix has failed.  Do not restart fetchmail, just return
            return $retstatus
        fi

        systemctl start fetchmail
        tempstatus=$?
        if [ $tempstatus -ne 0 ]
        then
            logger -s -t $0 "Could not restart fetchmail: $tempstatus"
            retstatus=$tempstatus
        fi
    else
        echo "$0 internal error: invalid hook argument $1"
        retstatus=97
    fi

    return $retstatus
    
}

count=0
seconds=0
portion_start="$(date --utc +%s)"
while run-portion "$@"
do
    count=$((count+1))
    portion_end="$(date --utc +%s)"
    seconds=$((seconds + 1 + portion_end - portion_start))
    
    [ -n "$limit" ] && [ "$limit" -gt 0 ] && [ "$count" -ge "$limit" ] && echo "Limit reached: $limit" && break
    [ -n "$tlimit" ] && [ "$tlimit" -gt 0 ] && [ "$seconds" -ge "$tlimit" ] && echo "Time limit reached: $tlimit seconds" && break
    
    sleep ${interval}s
    portion_start="$(date --utc +%s)"
done

echo "Balance completed in $count portions, $seconds seconds"
